//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassesJoinUser
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string SchoolComment { get; set; }
        public int ClassId { get; set; }
        public string ClassComment { get; set; }
        public string ClassName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<System.DateTime> LastDateOfStatusChange { get; set; }
        public string factor { get; set; }
    }
}
