//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProffestionJoinTeacher
    {
        public string TeacherName { get; set; }
        public int TeacherId { get; set; }
        public int ProffestionId { get; set; }
        public string ProffestionName { get; set; }
        public string Checked { get; set; }
    }
}
