//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToClass
    {
        public int UserId { get; set; }
        public string ClassName { get; set; }
        public string school { get; set; }
        public int id { get; set; }
        public int idUser { get; set; }
        public int idClass { get; set; }
    
        public virtual User User { get; set; }
        public virtual ClassToSchool ClassToSchool { get; set; }
        public virtual Users Users { get; set; }
    }
}
