//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public string AnswerId { get; set; }
        public string QuestionId { get; set; }
        public string UserId { get; set; }
        public string AnswerContant { get; set; }
        public string AnswerScoring { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual User User { get; set; }
    }
}
